services:
  app:
    image: adminmeetaza/prime-face-recognizer:latest
    build: .
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - deepface_weights:/root/.deepface/weights
volumes:
  deepface_weights:
